# Generated by Django 3.1.2 on 2020-11-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charcode', models.CharField(max_length=10, verbose_name='Код валюты')),
                ('name', models.CharField(max_length=30, verbose_name='Название валюты')),
            ],
        ),
    ]
